import { Root } from "@/components/Layout";
import Nav from "@/components/Nav";
import "@css/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className="flex flex-col w-full h-screen bg-white dark:bg-zinc-900 text-gray-900 dark:text-gray-100 antialiased max-w-4xl mx-auto">
        <Nav />
        <Root>{children}</Root>
      </body>
    </html>
  );
}
